on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - 'composer.json'
      - 'composer.lock'
      - 'phpunit.xml'
      - 'phpstan.neon'
      - 'phpcs.xml'
      - '.github/workflows/ci.yml'
      - 'makefile'
      - '.env'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - 'composer.json'
      - 'composer.lock'
      - 'phpunit.xml'
      - 'phpstan.neon'
      - 'phpcs.xml'
      - '.github/workflows/ci.yml'
      - 'makefile'
      - '.env'
  workflow_dispatch:

jobs:
  build-and-test:
    name: Jardis DotEnv - Run Build, QA Tools and Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        env:
          DOCKER_CONFIG: /tmp/.docker
        run: |
          mkdir -p $DOCKER_CONFIG
          echo "${{ secrets.DOCKER_PAT }}" | docker login -u "${{ secrets.DOCKER_USER_NAME }}" --password-stdin

      - name: Install dependencies
        run: make install

      - name: Regenerate autoloader
        run: make autoload

      - name: Check Code Standards with PHPCS
        run: make phpcs

      - name: Run PHPUnit Tests with Coverage
        env:
          HOME: /home/runner
        run: make phpunit-coverage

      - name: Run PHPStan (Static Analysis)
        run: make phpstan

      - name: Tear Down Docker Environment
        if: always()
        run: make remove

      - name: Logout from Docker Hub
        if: always()
        env:
          DOCKER_CONFIG: /tmp/.docker
        run: docker logout
